In [1]:
import pandas as pd
import numpy as np

import keras
from tensorflow.keras import models,layers

import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import OneHotEncoder


Using TensorFlow backend.


# Problem 2

In [2]:
Train_X = pd.read_csv('Data for Problem 2/data/trainx.csv',header=None)
Train_y = pd.read_csv('Data for Problem 2/data/trainy.csv',header=None)
Test_x = pd.read_csv('Data for Problem 2/data/testx.csv',header=None)
Test_y = pd.read_csv('Data for Problem 2/data/testy.csv',header=None)

In [3]:
problem2_model = MLPClassifier(random_state=1, max_iter=300,hidden_layer_sizes=100)
problem2_model.fit(Train_X,Train_y)

/Users/masoudkhani/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=100, learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=300,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=1, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [4]:
p2_predictions = problem2_model.predict(Test_x)
print(confusion_matrix(Test_y,p2_predictions))
print(classification_report(Test_y,p2_predictions))

[[84 24]
 [12 80]]
              precision    recall  f1-score   support

           0       0.88      0.78      0.82       108
           1       0.77      0.87      0.82        92

    accuracy                           0.82       200
   macro avg       0.82      0.82      0.82       200
weighted avg       0.83      0.82      0.82       200



#### in this problem, we do not get better accuracy than Logistic Regression(for MLP model). Basically using Neural Network is not the best way always. In some data using some traditional machine learning model is more sufficient.

In [5]:
problem2_model.coefs_[0]

array([[-0.12993322,  0.18103434, -0.2032315 ,  0.0219869 , -0.25141145,
        -0.40282281,  0.00096655, -0.08266044, -0.01698646, -0.01004403,
        -0.00747472,  0.0170392 , -0.20578597,  0.12767656, -0.22682579,
         0.30284594,  0.10449808, -0.02288077, -0.08133569, -0.09775281,
         0.09054816,  0.28859131, -0.05574962,  0.12224701,  0.35769494,
         0.05628181, -0.34762456, -0.14154275, -0.0419495 ,  0.20495355,
        -0.33765875,  0.06615468,  0.16386572,  0.08052058,  0.18409217,
         0.00507168,  0.02158804,  0.22299655, -0.17533921,  0.19022441,
         0.31956756,  0.14716011, -0.23248761,  0.26724008, -0.02216928,
        -0.08205398,  0.38952881, -0.05010705, -0.09812333, -0.03024539,
        -0.18616345,  0.14718336, -0.30710892, -0.00425316, -0.05028523,
        -0.08877782, -0.03978955, -0.32576113,  0.16928119,  0.1742764 ,
        -0.01804988, -0.052014  ,  0.15590496,  0.00776509, -0.33442405,
        -0.0071014 , -0.01540993,  0.22027653,  0.3

# problem 3

In [13]:
train_X = pd.read_csv('Data for Problem 3/data/trainx.csv',header=None)
train_y = pd.read_csv('Data for Problem 3/data/trainy.csv',header=None)
test_x = pd.read_csv('Data for Problem 3/data/testx.csv',header=None)
test_y = pd.read_csv('Data for Problem 3/data/testy.csv',header=None)

In [14]:
problem3_model = MLPClassifier(random_state=1, max_iter=300,hidden_layer_sizes=100)
problem3_model.fit(train_X,train_y)

/Users/masoudkhani/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=100, learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=300,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=1, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [15]:
p3_predictions = problem3_model.predict(test_x)
print(confusion_matrix(test_y,p3_predictions))
print(classification_report(test_y,p3_predictions))

[[162  33]
 [ 22 183]]
              precision    recall  f1-score   support

           0       0.88      0.83      0.85       195
           1       0.85      0.89      0.87       205

    accuracy                           0.86       400
   macro avg       0.86      0.86      0.86       400
weighted avg       0.86      0.86      0.86       400



In [16]:
problem3_model.coefs_[0]

array([[-0.21035939,  0.18806773, -0.17116772, -0.34072695, -0.32969718,
        -0.31849384, -0.12560301, -0.24285264, -0.11132426, -0.15886907,
        -0.2003599 , -0.00399163, -0.3209388 ,  0.15270715, -0.12091453,
         0.35338111,  0.00874992, -0.14511149, -0.30393363, -0.34506752,
         0.3685532 ,  0.25411122,  0.08993633,  0.25127284,  0.43856147,
         0.47702777, -0.21657258, -0.19762377, -0.39628762,  0.1250347 ,
        -0.23684522,  0.1210048 ,  0.40804199,  0.28343039,  0.26397601,
         0.06626981,  0.0353098 ,  0.11916546, -0.27588408,  0.38504667,
         0.23569498,  0.02337444, -0.27072047,  0.04522978, -0.06911285,
        -0.21835985,  0.10377101, -0.14168223, -0.26736622, -0.05157733,
        -0.43559971,  0.30295684, -0.20468612, -0.02020353, -0.20150172,
        -0.33641387, -0.09091026, -0.27647876,  0.2092628 ,  0.27400365,
        -0.11188301,  0.16160379,  0.27279306, -0.23494206, -0.38094213,
        -0.14216666, -0.04540401, -0.00109803,  0.3

#### As we can see we get almost dubble accuracy. Neural Netwok can devide the the points when they cannot be devided into different classes just by one line. In this case it is the same.

# Problem 4

In [56]:
TrainX = pd.read_csv('Data for Problem 4/train_input.csv',header=None)
TrainY = pd.read_csv('Data for Problem 4/train_labels.csv',header=None)
TestX = pd.read_csv('Data for Problem 4/test_input.csv',header=None)
TestY = pd.read_csv('Data for Problem 4/testy.csv')

In [84]:
problem4_model = MLPClassifier(random_state=2, max_iter=500,hidden_layer_sizes=200,epsilon=0.00003,solver='adam')
problem4_model.fit(TrainX,TrainY)

/Users/masoudkhani/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=3e-05,
              hidden_layer_sizes=200, learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=500,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=2, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [85]:
p4_predictions = problem4_model.predict(TestX)
print(confusion_matrix(TestY,p4_predictions))
print(classification_report(TestY,p4_predictions))

[[18  2  2]
 [ 4 22  1]
 [ 3  2 21]]
              precision    recall  f1-score   support

           1       0.72      0.82      0.77        22
           2       0.85      0.81      0.83        27
           3       0.88      0.81      0.84        26

    accuracy                           0.81        75
   macro avg       0.81      0.81      0.81        75
weighted avg       0.82      0.81      0.81        75

