In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score

# Problem 6 Home Work 2

In [3]:
Train_X = pd.read_csv('Problem 6/data/trainx.csv',header=None)
Train_y = pd.read_csv('Problem 6/data/trainy.csv',header=None)
Test_x = pd.read_csv('Problem 6/data/testx.csv',header=None)
Test_y = pd.read_csv('Problem 6/data/testy.csv',header=None)

In [5]:
Train_y = sklearn.utils.column_or_1d(Train_y, warn=True)
Test_y = sklearn.utils.column_or_1d(Test_y, warn=True)

Creating the model and fit the data into it

In [6]:
model = LogisticRegression(solver='liblinear', random_state=0)
model.fit(Train_X, Train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [7]:
predictions = model.predict(Test_x)

In [8]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(Test_y,predictions))
print(classification_report(Test_y,predictions))

[[84 24]
 [10 82]]
              precision    recall  f1-score   support

           0       0.89      0.78      0.83       108
           1       0.77      0.89      0.83        92

    accuracy                           0.83       200
   macro avg       0.83      0.83      0.83       200
weighted avg       0.84      0.83      0.83       200



In [9]:
model.classes_

array([0, 1])

#### weights of the two classes

In [10]:
model.coef_

array([[1.03477035, 0.48847307]])

# Problem 7 Home Work 2

In [11]:
train_X = pd.read_csv('Problem 7/data/trainx.csv',header=None)
train_y = pd.read_csv('Problem 7/data/trainy.csv',header=None)
test_x = pd.read_csv('Problem 7/data/testx.csv',header=None)
test_y = pd.read_csv('Problem 7/data/testy.csv',header=None)

In [13]:
train_y = sklearn.utils.column_or_1d(train_y, warn=True)
test_y = sklearn.utils.column_or_1d(test_y, warn=True)

In [14]:
model2 = LogisticRegression(solver='liblinear', random_state=0).fit(train_X, train_y)

In [15]:
predictions_problem7 = model2.predict(test_x)
print(confusion_matrix(test_y,predictions_problem7))
print(classification_report(test_y,predictions_problem7))

[[105  90]
 [137  68]]
              precision    recall  f1-score   support

           0       0.43      0.54      0.48       195
           1       0.43      0.33      0.37       205

    accuracy                           0.43       400
   macro avg       0.43      0.44      0.43       400
weighted avg       0.43      0.43      0.43       400



#### Based on Confusion matrix we can see that our model do not classify correctly and we have lot of false negetive and false positive. This could happen when we cannot sepprate two categories based on one line.

In [16]:
model2.classes_

array([0, 1])

In [17]:
model2.coef_

array([[ 0.02627383, -0.05689469]])