# Import Libraries

In [1]:
import numpy as np
import pandas as pd

#### Creating the graph

In [2]:
g = { 
        1: [2],
        2: [3],
        3: [1,4,5],
        4: [2,6],
        5: [],
        6: [7],
        7: [8],
        8: [6]
}

In [3]:
N = len(g)
print("graph length is :",N)

graph length is : 8


In [4]:
A = np.zeros((len(g),len(g)))
for i in range(1,9):
    for j in range(1,9):
        if len(g[i]) != 0 and j in g[i]:
            A[j-1,i-1] = 1/len(g[i])
pd.DataFrame(A)

0    1         2    3    4    5    6    7
0  0.0  0.0  0.333333  0.0  0.0  0.0  0.0  0.0
1  1.0  0.0  0.000000  0.5  0.0  0.0  0.0  0.0
2  0.0  1.0  0.000000  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.333333  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.333333  0.0  0.0  0.0  0.0  0.0
5  0.0  0.0  0.000000  0.5  0.0  0.0  0.0  1.0
6  0.0  0.0  0.000000  0.0  0.0  1.0  0.0  0.0
7  0.0  0.0  0.000000  0.0  0.0  0.0  1.0  0.0

#### we set our beta to 0.8 and for our threshold we use epsilon 0.01. In this project, our specific pages are 3 and 4.


In [6]:
beta = 0.8
epsilon = 0.01
# number of nodes
N = 8 
# Specific pages
s = [3,4]
s_length = len(s)

# First we code Standard PageRank

In [7]:
B = np.zeros((8,8))
B[:] = 1/N
B

array([[0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125],
       [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125]])

In [8]:
Al = beta * A + ((1-beta) * B)
pd.DataFrame(Al)

0      1         2      3      4      5      6      7
0  0.025  0.025  0.291667  0.025  0.025  0.025  0.025  0.025
1  0.825  0.025  0.025000  0.425  0.025  0.025  0.025  0.025
2  0.025  0.825  0.025000  0.025  0.025  0.025  0.025  0.025
3  0.025  0.025  0.291667  0.025  0.025  0.025  0.025  0.025
4  0.025  0.025  0.291667  0.025  0.025  0.025  0.025  0.025
5  0.025  0.025  0.025000  0.425  0.025  0.025  0.025  0.825
6  0.025  0.025  0.025000  0.025  0.025  0.825  0.025  0.025
7  0.025  0.025  0.025000  0.025  0.025  0.025  0.825  0.025

In [9]:
r = np.zeros((1,8)).T
r[:] = 1/N
r

array([[0.125],
       [0.125],
       [0.125],
       [0.125],
       [0.125],
       [0.125],
       [0.125],
       [0.125]])

In [10]:
diff = np.infty
iterration = 0
while diff > epsilon:
    r_old = r
    new_r = r = np.dot(Al,r)
    diff = sum(abs(new_r - r_old))
    iterration +=1
print("Done", iterration)
r

Done 32


array([[0.01149383],
       [0.01980517],
       [0.02195315],
       [0.01149383],
       [0.01149383],
       [0.04468334],
       [0.04284297],
       [0.04119402]])

# Page Specific

#### for page specific we just need to calculate the Matrix "Al" For specific pages number 3 and 4


In [11]:
AS = np.zeros((8,8))
for i in range(N):
    for j in range(N):
        # we set i+1 because the index is starting from 0
        if i+1 in s:
            AS[i,j] = beta * A[i,j] + ((1-beta)/s_length)
        else:
            AS[i,j] = beta * A[i,j]
pd.DataFrame(AS)

0    1         2    3    4    5    6    7
0  0.0  0.0  0.266667  0.0  0.0  0.0  0.0  0.0
1  0.8  0.0  0.000000  0.4  0.0  0.0  0.0  0.0
2  0.1  0.9  0.100000  0.1  0.1  0.1  0.1  0.1
3  0.1  0.1  0.366667  0.1  0.1  0.1  0.1  0.1
4  0.0  0.0  0.266667  0.0  0.0  0.0  0.0  0.0
5  0.0  0.0  0.000000  0.4  0.0  0.0  0.0  0.8
6  0.0  0.0  0.000000  0.0  0.0  0.8  0.0  0.0
7  0.0  0.0  0.000000  0.0  0.0  0.0  0.8  0.0

In [12]:
R = np.zeros((1,8)).T
R[:] = 1/N

In [13]:
different = np.infty
iteration = 0
while different > epsilon:
    R_old = R 
    new_R = R = np.dot(AS,R)
    different = sum(abs(new_R - R_old))
    iteration+=1
print("Completed after",iteration, "iteration")
R

Completed after 33 iteration


array([[0.01163534],
       [0.02374321],
       [0.0416821 ],
       [0.03343409],
       [0.01163534],
       [0.03390968],
       [0.02839736],
       [0.02380664]])